version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Ajusta el puerto según sea necesario
    volumes:
      - ./app_data:/app/data  # Bind mount para compartir archivos entre el host y el contenedor
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    stdin_open: true
    tty: true
